### ISSUE TITLE
Build Link Generation broken for units with Latent Abilities

### ISSUE THREAD

**Issue by Darwe-Canine** [lyrgard/ffbeEquip#382] opened 2019-08-01 00:00 UTC
The builder can't generate URLs for unit/team builds where the units have latent abilities activated; if they are marked as "not unlocked", it still works.

**Comment by jnievelt** [comment] 2019-08-08 05:11
Root cause here is that it's trying to get a link for enhancement level 3, while the back end only supports enhancements up to level 2. Quick fix would be to allow level 3; not sure if we want a more complete solution here, i.e., to respect the max level of 2 for non-SBB abilities while allowing SBB abilities to go to 3.

**Comment by jnievelt** [comment] 2019-08-09 15:38
Fixed in a4bf44c, which seems to be live now.

**Closed** 2019-08-20 18:18 UTC
